# Generated by Django 3.0.1 on 2020-01-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191231_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Classes'),
        ),
    ]
