# Generated by Django 3.0.1 on 2020-01-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200101_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='profile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
