# Generated by Django 3.0.1 on 2020-01-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200101_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=None, verbose_name=''),
        ),
        migrations.AddField(
            model_name='teachers',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=None, verbose_name=''),
        ),
    ]
